[package]
name = "pilgo"
version = "0.6.0"
authors = ["Gabriel Sanches <gabriel@gsr.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
pretty_assertions = "0.6.1"
